### ISSUE TITLE
Missing example env

### ISSUE THREAD

**Issue by valoricDe** [NextJSTemplates/docs-feedback#3]
When I clone I don't know which env variables I have to fill out. Not all variables in the docs have the right name or are mentioned.

I think it would be nice to have a .env.example which lists all env variables without the values

**Comment by Coderamrin** [comment]
Yes, it's available on all the templates. 
Can you please tell me the name of the template?
I will update it ASAP. 

@valoricDe 

Thanks

**Comment by valoricDe** [comment]
solid-nextjs pro version

**Comment by Coderamrin** [comment]
As I can see it has the example.env file

![image](https://github.com/user-attachments/assets/9a91d5e6-1614-4d8e-a635-7d5888862fd7)

**Comment by valoricDe** [comment]
I just downloaded from nextjstemplates the payed version "Solid_-_Next.js_SaaS_Boilerplate_and_Starter_Kit" again and it does not contain integration.config.tsx and no .env.example.
Does this need to be synced with the repo?

**Comment by Coderamrin** [comment]
The example env file was removed for some reason. The integration.config.tsx is just a new integration we added last week, it wasn't updated then. 
But the file is now updated. You can download it and try again.

**Comment by valoricDe** [comment]
Thank you
